// Agentic Pricing Demo - Data
const pricingData = [
  {
    "SKU_ID": "SKU-1000",
    "Product_Name": "Product_0",
    "Category": "Accessories",
    "Region": "North",
    "Current_Price": 4390,
    "Suggested_Price": 1495,
    "Competitor_Price": 2070,
    "Demand_Index": 1.31,
    "Elasticity": -0.73,
    "Inventory_Level": 522,
    "Confidence_Score": 0.76,
    "Recommendation_Type": "Hold",
    "Expected_Revenue_Impact_%": -2.36,
    "Agent_Rationale": "Overstock detected in DC2"
  },
  {
    "SKU_ID": "SKU-1001",
    "Product_Name": "Product_1",
    "Category": "Outerwear",
    "Region": "North",
    "Current_Price": 1146,
    "Suggested_Price": 3842,
    "Competitor_Price": 3190,
    "Demand_Index": 1.4,
    "Elasticity": -2.4,
    "Inventory_Level": 995,
    "Confidence_Score": 0.95,
    "Recommendation_Type": "Hold",
    "Expected_Revenue_Impact_%": -5.23,
    "Agent_Rationale": "Upcoming campaign alignment"
  },
  {
    "SKU_ID": "SKU-1002",
    "Product_Name": "Product_2",
    "Category": "Apparel",
    "Region": "North",
    "Current_Price": 1804,
    "Suggested_Price": 2341,
    "Competitor_Price": 2850,
    "Demand_Index": 1.28,
    "Elasticity": -1.52,
    "Inventory_Level": 138,
    "Confidence_Score": 0.71,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 8.42,
    "Agent_Rationale": "Strong market positioning opportunity"
  },
  {
    "SKU_ID": "SKU-1003",
    "Product_Name": "Product_3",
    "Category": "Footwear",
    "Region": "North",
    "Current_Price": 2633,
    "Suggested_Price": 3508,
    "Competitor_Price": 1970,
    "Demand_Index": 1.04,
    "Elasticity": -0.54,
    "Inventory_Level": 740,
    "Confidence_Score": 0.88,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 4.19,
    "Agent_Rationale": "Low competition pricing advantage"
  },
  {
    "SKU_ID": "SKU-1004",
    "Product_Name": "Product_4",
    "Category": "Accessories",
    "Region": "West",
    "Current_Price": 4902,
    "Suggested_Price": 4169,
    "Competitor_Price": 2490,
    "Demand_Index": 0.58,
    "Elasticity": -1.06,
    "Inventory_Level": 689,
    "Confidence_Score": 0.82,
    "Recommendation_Type": "Decrease",
    "Expected_Revenue_Impact_%": 7.35,
    "Agent_Rationale": "Price sensitivity threshold exceeded"
  },
  {
    "SKU_ID": "SKU-1005",
    "Product_Name": "Product_5",
    "Category": "Outerwear",
    "Region": "West",
    "Current_Price": 1639,
    "Suggested_Price": 2544,
    "Competitor_Price": 1320,
    "Demand_Index": 1.42,
    "Elasticity": -1.93,
    "Inventory_Level": 394,
    "Confidence_Score": 0.77,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 6.28,
    "Agent_Rationale": "High demand with inventory cushion"
  },
  {
    "SKU_ID": "SKU-1006",
    "Product_Name": "Product_6",
    "Category": "Apparel",
    "Region": "West",
    "Current_Price": 3226,
    "Suggested_Price": 3903,
    "Competitor_Price": 4620,
    "Demand_Index": 1.11,
    "Elasticity": -1.24,
    "Inventory_Level": 914,
    "Confidence_Score": 0.84,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 3.94,
    "Agent_Rationale": "Competitor benchmark analysis supports increase"
  },
  {
    "SKU_ID": "SKU-1007",
    "Product_Name": "Product_7",
    "Category": "Footwear",
    "Region": "West",
    "Current_Price": 3988,
    "Suggested_Price": 3217,
    "Competitor_Price": 4020,
    "Demand_Index": 0.81,
    "Elasticity": -0.64,
    "Inventory_Level": 178,
    "Confidence_Score": 0.9,
    "Recommendation_Type": "Decrease",
    "Expected_Revenue_Impact_%": 5.81,
    "Agent_Rationale": "Volume optimization recommended"
  },
  {
    "SKU_ID": "SKU-1008",
    "Product_Name": "Product_8",
    "Category": "Accessories",
    "Region": "South",
    "Current_Price": 4631,
    "Suggested_Price": 3947,
    "Competitor_Price": 4260,
    "Demand_Index": 0.92,
    "Elasticity": -0.88,
    "Inventory_Level": 548,
    "Confidence_Score": 0.79,
    "Recommendation_Type": "Decrease",
    "Expected_Revenue_Impact_%": 4.67,
    "Agent_Rationale": "Competitive pressure adjustment needed"
  },
  {
    "SKU_ID": "SKU-1009",
    "Product_Name": "Product_9",
    "Category": "Outerwear",
    "Region": "South",
    "Current_Price": 1397,
    "Suggested_Price": 1948,
    "Competitor_Price": 2780,
    "Demand_Index": 1.26,
    "Elasticity": -2.15,
    "Inventory_Level": 826,
    "Confidence_Score": 0.86,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 7.13,
    "Agent_Rationale": "Market gap exploitation opportunity"
  },
  {
    "SKU_ID": "SKU-1010",
    "Product_Name": "Product_10",
    "Category": "Apparel",
    "Region": "South",
    "Current_Price": 2142,
    "Suggested_Price": 2784,
    "Competitor_Price": 1890,
    "Demand_Index": 1.19,
    "Elasticity": -1.38,
    "Inventory_Level": 452,
    "Confidence_Score": 0.73,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 5.56,
    "Agent_Rationale": "Premium positioning viable"
  },
  {
    "SKU_ID": "SKU-1011",
    "Product_Name": "Product_11",
    "Category": "Footwear",
    "Region": "South",
    "Current_Price": 3451,
    "Suggested_Price": 4176,
    "Competitor_Price": 3630,
    "Demand_Index": 1.08,
    "Elasticity": -0.79,
    "Inventory_Level": 291,
    "Confidence_Score": 0.91,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 3.28,
    "Agent_Rationale": "Brand strength supports premium pricing"
  },
  {
    "SKU_ID": "SKU-1012",
    "Product_Name": "Product_12",
    "Category": "Accessories",
    "Region": "East",
    "Current_Price": 4218,
    "Suggested_Price": 3556,
    "Competitor_Price": 3940,
    "Demand_Index": 0.74,
    "Elasticity": -0.97,
    "Inventory_Level": 613,
    "Confidence_Score": 0.87,
    "Recommendation_Type": "Decrease",
    "Expected_Revenue_Impact_%": 6.42,
    "Agent_Rationale": "Demand elasticity requires adjustment"
  },
  {
    "SKU_ID": "SKU-1013",
    "Product_Name": "Product_13",
    "Category": "Outerwear",
    "Region": "East",
    "Current_Price": 1528,
    "Suggested_Price": 2163,
    "Competitor_Price": 2460,
    "Demand_Index": 1.33,
    "Elasticity": -2.08,
    "Inventory_Level": 771,
    "Confidence_Score": 0.81,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 6.85,
    "Agent_Rationale": "Seasonal demand surge predicted"
  },
  {
    "SKU_ID": "SKU-1014",
    "Product_Name": "Product_14",
    "Category": "Apparel",
    "Region": "East",
    "Current_Price": 2897,
    "Suggested_Price": 3462,
    "Competitor_Price": 3210,
    "Demand_Index": 1.15,
    "Elasticity": -1.41,
    "Inventory_Level": 526,
    "Confidence_Score": 0.76,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 4.73,
    "Agent_Rationale": "Quality perception justifies increase"
  },
  {
    "SKU_ID": "SKU-1015",
    "Product_Name": "Product_15",
    "Category": "Footwear",
    "Region": "East",
    "Current_Price": 3762,
    "Suggested_Price": 4389,
    "Competitor_Price": 4850,
    "Demand_Index": 1.06,
    "Elasticity": -0.68,
    "Inventory_Level": 345,
    "Confidence_Score": 0.93,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 2.97,
    "Agent_Rationale": "Underpriced vs competition"
  },
  {
    "SKU_ID": "SKU-1016",
    "Product_Name": "Product_16",
    "Category": "Accessories",
    "Region": "North",
    "Current_Price": 4557,
    "Suggested_Price": 5142,
    "Competitor_Price": 5630,
    "Demand_Index": 0.89,
    "Elasticity": -1.12,
    "Inventory_Level": 482,
    "Confidence_Score": 0.69,
    "Recommendation_Type": "Hold",
    "Expected_Revenue_Impact_%": -1.84,
    "Agent_Rationale": "Market uncertainty requires monitoring"
  },
  {
    "SKU_ID": "SKU-1017",
    "Product_Name": "Product_17",
    "Category": "Outerwear",
    "Region": "North",
    "Current_Price": 1753,
    "Suggested_Price": 2298,
    "Competitor_Price": 2940,
    "Demand_Index": 1.37,
    "Elasticity": -1.86,
    "Inventory_Level": 658,
    "Confidence_Score": 0.83,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 7.56,
    "Agent_Rationale": "Competitor weakness identified"
  },
  {
    "SKU_ID": "SKU-1018",
    "Product_Name": "Product_18",
    "Category": "Apparel",
    "Region": "West",
    "Current_Price": 2513,
    "Suggested_Price": 3187,
    "Competitor_Price": 2870,
    "Demand_Index": 1.23,
    "Elasticity": -1.59,
    "Inventory_Level": 397,
    "Confidence_Score": 0.78,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 5.91,
    "Agent_Rationale": "Value perception supports higher price"
  },
  {
    "SKU_ID": "SKU-1019",
    "Product_Name": "Product_19",
    "Category": "Footwear",
    "Region": "West",
    "Current_Price": 3184,
    "Suggested_Price": 2847,
    "Competitor_Price": 3560,
    "Demand_Index": 0.86,
    "Elasticity": -0.71,
    "Inventory_Level": 219,
    "Confidence_Score": 0.89,
    "Recommendation_Type": "Decrease",
    "Expected_Revenue_Impact_%": 5.14,
    "Agent_Rationale": "Market share expansion strategy"
  },
  {
    "SKU_ID": "SKU-1020",
    "Product_Name": "Product_20",
    "Category": "Accessories",
    "Region": "South",
    "Current_Price": 4893,
    "Suggested_Price": 5467,
    "Competitor_Price": 4720,
    "Demand_Index": 0.95,
    "Elasticity": -1.03,
    "Inventory_Level": 574,
    "Confidence_Score": 0.72,
    "Recommendation_Type": "Hold",
    "Expected_Revenue_Impact_%": -3.12,
    "Agent_Rationale": "Regional pricing review pending"
  },
  {
    "SKU_ID": "SKU-1021",
    "Product_Name": "Product_21",
    "Category": "Outerwear",
    "Region": "South",
    "Current_Price": 1482,
    "Suggested_Price": 2076,
    "Competitor_Price": 2550,
    "Demand_Index": 1.29,
    "Elasticity": -1.97,
    "Inventory_Level": 703,
    "Confidence_Score": 0.85,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 6.69,
    "Agent_Rationale": "Strong brand equity leverage point"
  },
  {
    "SKU_ID": "SKU-1022",
    "Product_Name": "Product_22",
    "Category": "Apparel",
    "Region": "East",
    "Current_Price": 2671,
    "Suggested_Price": 3254,
    "Competitor_Price": 3090,
    "Demand_Index": 1.17,
    "Elasticity": -1.47,
    "Inventory_Level": 468,
    "Confidence_Score": 0.74,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 5.22,
    "Agent_Rationale": "Fashion trend alignment"
  },
  {
    "SKU_ID": "SKU-1023",
    "Product_Name": "Product_23",
    "Category": "Footwear",
    "Region": "East",
    "Current_Price": 3599,
    "Suggested_Price": 4214,
    "Competitor_Price": 4390,
    "Demand_Index": 1.09,
    "Elasticity": -0.82,
    "Inventory_Level": 312,
    "Confidence_Score": 0.92,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 3.45,
    "Agent_Rationale": "Product lifecycle optimization"
  },
  {
    "SKU_ID": "SKU-1024",
    "Product_Name": "Product_24",
    "Category": "Accessories",
    "Region": "North",
    "Current_Price": 4379,
    "Suggested_Price": 3728,
    "Competitor_Price": 4150,
    "Demand_Index": 0.78,
    "Elasticity": -0.93,
    "Inventory_Level": 641,
    "Confidence_Score": 0.88,
    "Recommendation_Type": "Decrease",
    "Expected_Revenue_Impact_%": 6.18,
    "Agent_Rationale": "Customer acquisition focus"
  },
  {
    "SKU_ID": "SKU-1025",
    "Product_Name": "Product_25",
    "Category": "Outerwear",
    "Region": "West",
    "Current_Price": 1616,
    "Suggested_Price": 1843,
    "Competitor_Price": 2680,
    "Demand_Index": 1.35,
    "Elasticity": -2.11,
    "Inventory_Level": 887,
    "Confidence_Score": 0.67,
    "Recommendation_Type": "Hold",
    "Expected_Revenue_Impact_%": -4.57,
    "Agent_Rationale": "Inventory clearance timing conflict"
  },
  {
    "SKU_ID": "SKU-1026",
    "Product_Name": "Product_26",
    "Category": "Apparel",
    "Region": "West",
    "Current_Price": 2386,
    "Suggested_Price": 2914,
    "Competitor_Price": 3340,
    "Demand_Index": 1.21,
    "Elasticity": -1.56,
    "Inventory_Level": 535,
    "Confidence_Score": 0.79,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 5.64,
    "Agent_Rationale": "Category dominance opportunity"
  },
  {
    "SKU_ID": "SKU-1027",
    "Product_Name": "Product_27",
    "Category": "Footwear",
    "Region": "South",
    "Current_Price": 3318,
    "Suggested_Price": 3976,
    "Competitor_Price": 4180,
    "Demand_Index": 1.12,
    "Elasticity": -0.76,
    "Inventory_Level": 264,
    "Confidence_Score": 0.94,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 3.61,
    "Agent_Rationale": "Supply constraint creates pricing power"
  },
  {
    "SKU_ID": "SKU-1028",
    "Product_Name": "Product_28",
    "Category": "Accessories",
    "Region": "South",
    "Current_Price": 4746,
    "Suggested_Price": 5328,
    "Competitor_Price": 5490,
    "Demand_Index": 0.91,
    "Elasticity": -1.09,
    "Inventory_Level": 609,
    "Confidence_Score": 0.71,
    "Recommendation_Type": "Hold",
    "Expected_Revenue_Impact_%": -2.73,
    "Agent_Rationale": "Cross-category promotion planned"
  },
  {
    "SKU_ID": "SKU-1029",
    "Product_Name": "Product_29",
    "Category": "Outerwear",
    "Region": "East",
    "Current_Price": 1694,
    "Suggested_Price": 2419,
    "Competitor_Price": 2820,
    "Demand_Index": 1.38,
    "Elasticity": -1.89,
    "Inventory_Level": 749,
    "Confidence_Score": 0.82,
    "Recommendation_Type": "Increase",
    "Expected_Revenue_Impact_%": 7.28,
    "Agent_Rationale": "Weather forecast supports demand spike"
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { pricingData };
}